# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coris.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'coris.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63oris.proto\x12\x02pb\"0\n\x0e\x43ommandRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08is_voice\x18\x02 \x01(\x08\"Y\n\x0f\x43ommandResponse\x12\x17\n\x0fspeech_feedback\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12\x1f\n\x08\x61ssembly\x18\x03 \x03(\x0b\x32\r.pb.Component\"z\n\tComponent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x10\n\x08position\x18\x03 \x03(\x02\x12\r\n\x05scale\x18\x04 \x03(\x02\x12\r\n\x05\x63olor\x18\x05 \x01(\t\x12#\n\x08material\x18\x06 \x01(\x0b\x32\x11.pb.MaterialProps\"H\n\rMaterialProps\x12\x11\n\troughness\x18\x01 \x01(\x02\x12\x11\n\tmetalness\x18\x02 \x01(\x02\x12\x11\n\tclearcoat\x18\x03 \x01(\x02\x32\x46\n\x0c\x43orisService\x12\x36\n\x0bSendCommand\x12\x12.pb.CommandRequest\x1a\x13.pb.CommandResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coris_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_COMMANDREQUEST']._serialized_start=19
  _globals['_COMMANDREQUEST']._serialized_end=67
  _globals['_COMMANDRESPONSE']._serialized_start=69
  _globals['_COMMANDRESPONSE']._serialized_end=158
  _globals['_COMPONENT']._serialized_start=160
  _globals['_COMPONENT']._serialized_end=282
  _globals['_MATERIALPROPS']._serialized_start=284
  _globals['_MATERIALPROPS']._serialized_end=356
  _globals['_CORISSERVICE']._serialized_start=358
  _globals['_CORISSERVICE']._serialized_end=428
# @@protoc_insertion_point(module_scope)
