// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: coris.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	IsVoice       bool                   `protobuf:"varint,2,opt,name=is_voice,json=isVoice,proto3" json:"is_voice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_coris_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coris_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_coris_proto_rawDescGZIP(), []int{0}
}

func (x *CommandRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CommandRequest) GetIsVoice() bool {
	if x != nil {
		return x.IsVoice
	}
	return false
}

type CommandResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SpeechFeedback string                 `protobuf:"bytes,1,opt,name=speech_feedback,json=speechFeedback,proto3" json:"speech_feedback,omitempty"`
	Mode           string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"` // "REPLACE" atau "APPEND"
	Assembly       []*Component           `protobuf:"bytes,3,rep,name=assembly,proto3" json:"assembly,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_coris_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coris_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_coris_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResponse) GetSpeechFeedback() string {
	if x != nil {
		return x.SpeechFeedback
	}
	return ""
}

func (x *CommandResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CommandResponse) GetAssembly() []*Component {
	if x != nil {
		return x.Assembly
	}
	return nil
}

type Component struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                  // box, sphere, cylinder, cone
	Position      []float32              `protobuf:"fixed32,3,rep,packed,name=position,proto3" json:"position,omitempty"` // [x, y, z]
	Scale         []float32              `protobuf:"fixed32,4,rep,packed,name=scale,proto3" json:"scale,omitempty"`       // [x, y, z]
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`                // Hex code
	Material      *MaterialProps         `protobuf:"bytes,6,opt,name=material,proto3" json:"material,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Component) Reset() {
	*x = Component{}
	mi := &file_coris_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_coris_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_coris_proto_rawDescGZIP(), []int{2}
}

func (x *Component) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Component) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Component) GetPosition() []float32 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Component) GetScale() []float32 {
	if x != nil {
		return x.Scale
	}
	return nil
}

func (x *Component) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Component) GetMaterial() *MaterialProps {
	if x != nil {
		return x.Material
	}
	return nil
}

type MaterialProps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roughness     float32                `protobuf:"fixed32,1,opt,name=roughness,proto3" json:"roughness,omitempty"`
	Metalness     float32                `protobuf:"fixed32,2,opt,name=metalness,proto3" json:"metalness,omitempty"`
	Clearcoat     float32                `protobuf:"fixed32,3,opt,name=clearcoat,proto3" json:"clearcoat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterialProps) Reset() {
	*x = MaterialProps{}
	mi := &file_coris_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterialProps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialProps) ProtoMessage() {}

func (x *MaterialProps) ProtoReflect() protoreflect.Message {
	mi := &file_coris_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialProps.ProtoReflect.Descriptor instead.
func (*MaterialProps) Descriptor() ([]byte, []int) {
	return file_coris_proto_rawDescGZIP(), []int{3}
}

func (x *MaterialProps) GetRoughness() float32 {
	if x != nil {
		return x.Roughness
	}
	return 0
}

func (x *MaterialProps) GetMetalness() float32 {
	if x != nil {
		return x.Metalness
	}
	return 0
}

func (x *MaterialProps) GetClearcoat() float32 {
	if x != nil {
		return x.Clearcoat
	}
	return 0
}

var File_coris_proto protoreflect.FileDescriptor

const file_coris_proto_rawDesc = "" +
	"\n" +
	"\vcoris.proto\x12\x02pb\"?\n" +
	"\x0eCommandRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\bis_voice\x18\x02 \x01(\bR\aisVoice\"y\n" +
	"\x0fCommandResponse\x12'\n" +
	"\x0fspeech_feedback\x18\x01 \x01(\tR\x0espeechFeedback\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12)\n" +
	"\bassembly\x18\x03 \x03(\v2\r.pb.ComponentR\bassembly\"\xa6\x01\n" +
	"\tComponent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bposition\x18\x03 \x03(\x02R\bposition\x12\x14\n" +
	"\x05scale\x18\x04 \x03(\x02R\x05scale\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x12-\n" +
	"\bmaterial\x18\x06 \x01(\v2\x11.pb.MaterialPropsR\bmaterial\"i\n" +
	"\rMaterialProps\x12\x1c\n" +
	"\troughness\x18\x01 \x01(\x02R\troughness\x12\x1c\n" +
	"\tmetalness\x18\x02 \x01(\x02R\tmetalness\x12\x1c\n" +
	"\tclearcoat\x18\x03 \x01(\x02R\tclearcoat2F\n" +
	"\fCorisService\x126\n" +
	"\vSendCommand\x12\x12.pb.CommandRequest\x1a\x13.pb.CommandResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_coris_proto_rawDescOnce sync.Once
	file_coris_proto_rawDescData []byte
)

func file_coris_proto_rawDescGZIP() []byte {
	file_coris_proto_rawDescOnce.Do(func() {
		file_coris_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coris_proto_rawDesc), len(file_coris_proto_rawDesc)))
	})
	return file_coris_proto_rawDescData
}

var file_coris_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_coris_proto_goTypes = []any{
	(*CommandRequest)(nil),  // 0: pb.CommandRequest
	(*CommandResponse)(nil), // 1: pb.CommandResponse
	(*Component)(nil),       // 2: pb.Component
	(*MaterialProps)(nil),   // 3: pb.MaterialProps
}
var file_coris_proto_depIdxs = []int32{
	2, // 0: pb.CommandResponse.assembly:type_name -> pb.Component
	3, // 1: pb.Component.material:type_name -> pb.MaterialProps
	0, // 2: pb.CorisService.SendCommand:input_type -> pb.CommandRequest
	1, // 3: pb.CorisService.SendCommand:output_type -> pb.CommandResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_coris_proto_init() }
func file_coris_proto_init() {
	if File_coris_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coris_proto_rawDesc), len(file_coris_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coris_proto_goTypes,
		DependencyIndexes: file_coris_proto_depIdxs,
		MessageInfos:      file_coris_proto_msgTypes,
	}.Build()
	File_coris_proto = out.File
	file_coris_proto_goTypes = nil
	file_coris_proto_depIdxs = nil
}
