// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: coris.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CorisService_SendCommand_FullMethodName = "/pb.CorisService/SendCommand"
)

// CorisServiceClient is the client API for CorisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CorisServiceClient interface {
	SendCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
}

type corisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCorisServiceClient(cc grpc.ClientConnInterface) CorisServiceClient {
	return &corisServiceClient{cc}
}

func (c *corisServiceClient) SendCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, CorisService_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CorisServiceServer is the server API for CorisService service.
// All implementations must embed UnimplementedCorisServiceServer
// for forward compatibility.
type CorisServiceServer interface {
	SendCommand(context.Context, *CommandRequest) (*CommandResponse, error)
	mustEmbedUnimplementedCorisServiceServer()
}

// UnimplementedCorisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCorisServiceServer struct{}

func (UnimplementedCorisServiceServer) SendCommand(context.Context, *CommandRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedCorisServiceServer) mustEmbedUnimplementedCorisServiceServer() {}
func (UnimplementedCorisServiceServer) testEmbeddedByValue()                      {}

// UnsafeCorisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CorisServiceServer will
// result in compilation errors.
type UnsafeCorisServiceServer interface {
	mustEmbedUnimplementedCorisServiceServer()
}

func RegisterCorisServiceServer(s grpc.ServiceRegistrar, srv CorisServiceServer) {
	// If the following call panics, it indicates UnimplementedCorisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CorisService_ServiceDesc, srv)
}

func _CorisService_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorisServiceServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorisService_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorisServiceServer).SendCommand(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CorisService_ServiceDesc is the grpc.ServiceDesc for CorisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CorisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CorisService",
	HandlerType: (*CorisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCommand",
			Handler:    _CorisService_SendCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coris.proto",
}
